apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulator-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simulator
  template:
    metadata:
      labels:
        app: simulator
    spec:
      containers:
        - name: simulator
          image: atc-radar-sim-simulator_service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 4000
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: simulator-config
                  key: PORT
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: redis-config
                  key: redis-host
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: redis-config
                  key: redis-port
            - name: CORS_ORIGIN
              valueFrom:
                configMapKeyRef:
                  name: simulator-config
                  key: CORS_ORIGIN
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: simulator-secret
                  key: JWT_SECRET_KEY

---

apiVersion: v1
kind: Service
metadata:
  name: simulator-service
spec:
  type: NodePort
  selector:
    app: simulator
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 4000
      nodePort: 30002
